### ISSUE TITLE
Separate signal headers from their samples

### ISSUE THREAD

**Issue by OTDE** [beacon-biosignals/EDF.jl#25]
This is an important intermediary step in working towards memory mapping signals. I think it may be of use to do it in a similar way to Onda, where loading samples brings the associated signal header with it.

We'll need to add an `index_in_file` field either way, since the annotation signal can occur at any point in the signal order, intermixed with other signals' samples.

**Comment by ararslan** [comment]
Was this addressed in #23?

**Comment by OTDE** [comment]
no, but it will be addressed in the upcoming PR!

**Comment by jrevels** [comment]
closed by #26 AFAICT
