### ISSUE TITLE
Support BDF/BDF+

### ISSUE THREAD

**Issue by jrevels** [beacon-biosignals/EDF.jl#33]
BDF/BDF+ is essentially "24 bit EDF/EDF+": https://www.teuniz.net/edfbrowser/bdfplus%20format%20description.html

We could add a simple `bdf` flag to the `File` constructor (e.g. `File(io, bdf=true)`) and make sure to handle BDF-specific quirks on read/write. We should probably define a [simple `Int24` primitive type internally for storage](https://discourse.julialang.org/t/convert-to-and-from-int24/7670), and `decode` can handle it during conversion to floating point whenever any actual computation needs to be performed.

**Comment by palday** [comment]
I think BDF also limits some other things (e.g. requires constant sampling rate and includes a status channel), but it's the native format of Biosemi amplifiers, so we wind up supporting a huge class of research equipment. There's also GDF ..... There's a little bit on this over at bids-standard/pyEDF#2 .
